name: Deploy to AWS using CDK

on:
  push:
    branches:
      - main # or your default branch (e.g., master)
  pull_request:
    branches:
      - main # Trigger deployment when PR is merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Adjust as needed, ensure Node.js v18.x is installed

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Set your AWS credentials in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired region (e.g., us-west-2)

      - name: Install CDK dependencies
        run: npm install

      - name: Bootstrap AWS CDK
        run: cdk bootstrap --profile default # This is required only if you're deploying for the first time

      - name: Deploy CDK Stack
        run: |
          cdk deploy GenaiStack --require-approval never  # Replace 'GenaiStack' with the name of your stack class

      - name: Clean up
        run: |
          cdk destroy --force --no-rollback  # Optional, if you want to clean up after deploy (e.g., for testing environments)
